[book]
title = "RISC-V CPU Project"
authors = ["Gibreel"]
language = "ar"
src = "docs"

# ------------------------------------------------------------------------------
# Preprocessors Configuration
# ------------------------------------------------------------------------------
#[preprocessor.katex]
#[preprocessor.pdf]
[preprocessor.linkcheck]
[preprocessor.toc]

[preprocessor.mermaid]
command = "mdbook-mermaid"

# ------------------------------------------------------------------------------
# Output Configuration
# ------------------------------------------------------------------------------
[output.html]
html-dir = "rtl"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
